language: python
python:
  - "3.5"
  - "3.6"
services:
  - redis-server
env:
  - TEST_HIREDIS=0
  - TEST_HIREDIS=1
install:
  - pip install -e .
  - "if [[ $TEST_PEP8 == '1' ]]; then pip install pep8; fi"
  - "if [[ $TEST_HIREDIS == '1' ]]; then pip install hiredis; fi"
script: "if [[ $TEST_PEP8 == '1' ]]; then pep8 --repeat --show-source --exclude=.venv,.tox,dist,docs,build,*.egg .; else python setup.py test; fi"
matrix:
  include:
    - python: "3.5"
      env: TEST_PEP8=1