language: python
python:
  - "3.5"
  - "3.6"
services:
  - redis-server
env:
  - TEST_HIREDIS=0
  - TEST_HIREDIS=1
before_install:
  - pip install --upgrade pytest
install:
  - pip install -e .
  - "if [[ $TEST_HIREDIS == '1' ]]; then pip install hiredis; fi"
matrix:
  include:
    - python: "3.5"
